name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "sccache"
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: get MozillaBuild
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-4.0.2.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
        echo 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Tools\LLVM\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: cp build.sh to working dir
      shell: bash
      working-directory: ".."
      run: cp thunderbird-patches/build/build.sh .
    - name: Build
      working-directory: ".."
      # mozilla shell (start-shell.bat)
      env:
        MOZILLABUILD: 'C:\mozilla-build'
        PYTHON3: 'C:\mozilla-build\python3\python3.exe'
        MSYSTEM: MSYS
        CHERE_INVOKING: 'D:\a\thunderbird-patches'
      run: |
        C:\\mozilla-build\\usr\\bin\\bash.exe -leo pipefail "./build.sh 102"